# Generated by Django 2.2.6 on 2019-10-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('face', models.CharField(max_length=100000)),
            ],
        ),
    ]
