# Generated by Django 2.2.6 on 2019-10-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChangoFaceRec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='face',
            field=models.CharField(max_length=500000),
        ),
    ]
